a2_priority_queue
JaneRo19/Py-111 pull request #17
Opened 2022-03-15 21:30 UTC by JaneRo19

2022-03-16 14:41 UTC, EnotYoyo requested changes

2022-03-16 14:41 UTC, EnotYoyo commented on Tasks/a2_priority_queue.py
> +        for key, value in self.priority_queue.items():
Зачем так сложно? Вы же можете взять очередь по ключу и не нужно просматривать и искать нужный ключ :) 
В этом же суть словаря :)

2022-03-16 14:41 UTC, EnotYoyo commented on Tasks/a2_priority_queue.py
> +        self.priority_queue = {x: [] for x in range(11)}
Вот эту `11` можно вынести в параметры init. Тогда не будет магических констант в коде, а при желании можно будет без труда параметризовать очередь.

2022-03-16 14:41 UTC, EnotYoyo commented on Tasks/a2_priority_queue.py
> +        if self.priority_queue:
Словарь создается в init'e и в нем содержатся ключи. Поэтому эта проверка всегда будет проходить.

2022-03-16 14:41 UTC, EnotYoyo commented on Tasks/a2_priority_queue.py
> +        for key, value in self.priority_queue.items():
Аналогично. Взятие значения из словаря по ключу - простая операция, цикл не нужен

2022-03-17 22:31 UTC, JaneRo19 commented on Tasks/a2_priority_queue.py
> +        for key, value in self.priority_queue.items():
Поправила

2022-03-18 17:23 UTC, EnotYoyo approved these changes
Принято!

2022-03-18 18:37 UTC, merged