a3_check_brackets
JaneRo19/Py-111 pull request #7
Opened 2022-02-21 08:39 UTC by JaneRo19

2022-02-21 08:50 UTC, EnotYoyo approved these changes
можно было сделать проще, если хранить не сам стек, а только его длину :) 

То есть, по сути, зменить стек обычным счетчиком :)

2022-02-21 08:50 UTC, EnotYoyo commented on Tasks/a3_check_brackets.py
> +    if is_good and len(stack) == 0:
Конструкции такого вида:
```python 
  if is_good and len(stack) == 0:
      return True
  else:
      return False
```
Или общий вид конструкции: 
```python
if something:
    return True 
else:
    return False
```
Можно и нужно заменять на более короткую: 
```python
return is_good and len(stack) == 0
```

2022-02-21 08:50 UTC, EnotYoyo commented on Tasks/a3_check_brackets.py
> +            if open_bracket == "(" and ")":
непонятно, что за `and ")"`

2022-02-21 21:49 UTC, JaneRo19 commented on Tasks/a3_check_brackets.py
> +    if is_good and len(stack) == 0:
поправила, ошибки, переписала через счетчик, код больше понравился.

2022-02-21 21:49 UTC, JaneRo19 commented on Tasks/a3_check_brackets.py
> +            if open_bracket == "(" and ")":
здесь ошиблась, по-разному писала, не убрала лишнее

2022-02-21 22:38 UTC, EnotYoyo requested changes
В коде есть ошибка, посмотрите тесты.

2022-02-21 22:38 UTC, EnotYoyo commented on Tasks/a3_check_brackets.py
> +        if brackets_row[i] == "(" and brackets_row[0] != ")":
`and brackets_row[0] != ")" ` - первое условие гарантирует выполнение второго. Поэтому можно не проверять :)

2022-02-21 22:38 UTC, EnotYoyo commented on Tasks/a3_check_brackets.py
> +    for i in range(len(brackets_row)):
Тут лучше сразу по brackets_row итерироваться. Код будет еще проще

2022-02-21 22:38 UTC, EnotYoyo commented on Tasks/a3_check_brackets.py
> +    return True if counter == 0 else False
можно сразу `return counter ==0`

2022-02-21 23:03 UTC, EnotYoyo requested changes

2022-02-21 23:03 UTC, EnotYoyo commented on Tasks/a3_check_brackets.py
> +        if brackets_row[0] == ")":
Плохой фикс :) 

Можно придумать другой тест, который не начинается с такой скобки. 

Можно проверять, что counter не ушел "в минус"

2022-02-21 23:06 UTC, JaneRo19 commented on Tasks/a3_check_brackets.py
> +        if brackets_row[0] == ")":
подумаю еще, не могу сообразить как этой проверки избежать на первую скобку

2022-02-21 23:13 UTC, JaneRo19 commented on Tasks/a3_check_brackets.py
> +        if brackets_row[0] == ")":
поправила, проверяю счетчик на отрицательность, итерируюсь по brackets_row, от проверки первой скобки получилось избавиться

2022-02-22 19:44 UTC, EnotYoyo approved these changes
Супер! Принято! :)

2022-02-23 07:25 UTC, merged