c2_recursive_binary_search
JaneRo19/Py-111 pull request #8
Opened 2022-02-23 21:55 UTC by JaneRo19

2022-02-24 20:04 UTC, EnotYoyo requested changes
Реализованный алгоритм вернет индекс первого попавшегося элемента. А нужно самого левого элемента.

2022-03-12 08:22 UTC, EnotYoyo requested changes
А что для варианта: `[2,2,2,2,2,2,2,2,2,2,2,2,2]`. Ответом должен быть 0 (самый левый индекс)

2022-03-13 23:20 UTC, JaneRo19 commented
Поправила

2022-03-16 14:27 UTC, EnotYoyo approved these changes
Принято!

2022-03-16 21:03 UTC, merged