b2_Taylor
JaneRo19/Py-111 pull request #9
Opened 2022-02-23 23:41 UTC by JaneRo19

2022-02-24 20:05 UTC, EnotYoyo requested changes

2022-02-24 20:05 UTC, EnotYoyo commented on Tasks/b2_Taylor.py
> +    def get_item_n(n):
Тут возможна такая же оптимизация, как и в ex. Когда каждый последующий элемент получается с помощью предыдущего.

2022-02-24 22:17 UTC, JaneRo19 commented on Tasks/b2_Taylor.py
> +    def get_item_n(n):
посмотрю еще, пока не увидела зависимость, как можно использовать алгоритм быстрого возведения в степень

2022-02-24 23:28 UTC, EnotYoyo commented on Tasks/b2_Taylor.py
> +    def get_item_n(n):
Там есть зависимость. Поэтому реализовывать алгоритм не нужно. :)

2022-02-25 21:40 UTC, JaneRo19 commented on Tasks/b2_Taylor.py
> +    def get_item_n(n):
Попыталась исправить)

2022-02-26 07:42 UTC, EnotYoyo approved these changes
Принято!

2022-02-26 07:43 UTC, merged